version: '3.8'

services:
  web:
    build: ./docker/php
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
